global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prom
    static_configs:
      - targets: ['localhost:9090']
  - job_name: go-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:8000
